version: '3'
services:
    db:
        container_name: ${CONTAINER_NAME_DB}
        image: postgres:10.6
        environment:
            POSTGRES_USER: odoo
            POSTGRES_PASSWORD: odoo
            POSTGRES_DB: postgres
    odoo:
        container_name: ${CONTAINER_NAME_ODOO}
        image: ${ODOO_IMAGE}
        volumes:
            - ./entrypoint.sh:/entrypoint.sh
            - ./odoo.conf:/etc/odoo/odoo.conf
            - ${ODOO_MODULES}:/mnt/extra-addons
        depends_on:
            - db
        ports:
            - "${PORT_PREFIX}69:8069"
            - "${PORT_PREFIX}71:8071"
            - "${PORT_PREFIX}72:8072"
        tty: true
